### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ofilin86** [netom/pyicap#10]
Please write more examples :) Thanks

**Comment by davegermiquet** [comment]
I'm working on a project, 

What is the project your looking at to write? I'm trying to develop a open source icap filtering for content so children can not access adult content.

**Comment by netom** [comment]
Hi Dave,

I've created PyICAP as a general purpose Python ICAP framework.

I needed it for a client of ours, they needed to rewirte parts of the 
HTTP responses for their site, so they can include debugging version of 
javascript libraries even in production if needed.

Cheers,

Tamas

2016-09-29 16:47 keltezéssel, Dave Germiquet írta:
