### ISSUE TITLE
Is this project still open?

### ISSUE THREAD

**Issue by davegermiquet** [netom/pyicap#11]
I added this module to my project to make it be python 3 compatible (I'm unsure at the moment if it breaks Python 2).

Some of the code had to be changed:

xrange needs to be changed to be range
has_key had to be changed to in
print needed to have parenthesis.
and you need to encode the socket now instead of just passing a string.

However even with these changes at the moment I get connectionReset, periodically.l

**Comment by netom** [comment]
Hello Dave,

I don't actively developing PyICAP, it did it's job for me and I don't 
regularly update it.

I'm happy to receive any contribution though.

Thanks,

Tamas

2016-09-29 15:41 keltezéssel, Dave Germiquet írta:
