### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b

### ISSUE THREAD

**Issue by cahya-wirawan** [netom/pyicap#18]
Hi,

I use pyicap with python3.5, then I run "lynx google.com", but I got this error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128).
It breaks the code in pyicap.py: read_chunk(self): return value.decode('ascii')
It seems the response from google is encoded in 'ISO-8859-1' and not 'ascii'

**Comment by davegermiquet** [comment]
There's a couple problems with google. One of them this might be effecting is if you add the certificate that SQUID/ICAP server uses in your CHAIN so google knows its a trusted certificate.

Google doesn't accept non-trusted certificates..they are very secure.

So everyone who uses the icap server needs to have the trusted certificate.

**Comment by davegermiquet** [comment]
Additionally I had a branch that addressed some issues here:

github.com/davegermiquet/icapserverfiltering/commits/de/pyicap3/pyicap.py

Though I haven't looked at it in awhile I'll see if I can look at it tomorrow.

**Comment by davegermiquet** [comment]
Tried merging the pyicap.py with the one here seen below is the link:
github.com/davegermiquet/pyicap

Not sure if it works.

**Comment by cahya-wirawan** [comment]
Thanks, I will try it

**Comment by cahya-wirawan** [comment]
Sorr, I got this error: 
  File "../PycharmProjects/pyicap/pyicap.py", line 176, in read_chunk
    sel = selectors.PollSelector()
AttributeError: module 'selectors' has no attribute 'PollSelector'

**Comment by davegermiquet** [comment]
Ok I'll see if I can pull up a squid instance, set it up.

**Comment by davegermiquet** [comment]
I'll have another look on sunday. There were some issues with the rebase, and the version I was using..its been awhile since i've looked at this (sorry) 
I'll let you know if I succeed again with it.

**Comment by cahya-wirawan** [comment]
thank for your effort

**Comment by netom** [comment]
Thank you all for trying to make PyICAP work. I've just pushed 34a05673599f24e9fe2166d9d5b674cd4a817594 to master. Fixed tests and overall 2-3 compatibility. I started converting PyICAP to use bytes() internally, and to avoid encoding / decoding wherever it's possible.

**Comment by netom** [comment]
One of the biggest problems right now is the lack of tests. There *is* a tests.py, but it is about the shortest such file possible. :) My plan is to mock HTTP server and the request objects and simply use unittest with mock request instances. Issue #19 focuses on this issue. The encoding issue (this one) is pretty much depends on #19 since probably a lot of testing is needed for this to be solved properly.

**Comment by cahya-wirawan** [comment]
Great, thank for the fix, I will try it.

**Comment by cahya-wirawan** [comment]
Just tried it the example reqmod_copy.py, but I get following error:
  File "/PycharmProjects/pyicap/pyicap.py", line 331, in send_headers
    icap_header_str += b'\r\n'
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by netom** [comment]
That is normal at this point. The next step is to eliminate these errors by converting most (all?) of the string literals to byte literals, and using appropriate operators and algorithms while maintaining compatibility with recent Python 2-s. I'm happily accept patches along these lines.

**Comment by netom** [comment]
@cahya-wirawan thank you for the work on the str/bytes problem. After merging your commits I managed to make the reqmod examples work on both Python 2.7.12 and 3.5.2. Does anyone still having similar issues?

**Comment by netom** [comment]
I've released "1.0b1" on pypi, since no one reported any problems so far and there has been an explicit request to do so. Closing this issue.
