### ISSUE TITLE
Possible bug in reading requests

### ISSUE THREAD

**Issue by justinschw** [netom/pyicap#5]
Hi,

While writing a combined reqmod and respmod application, I have encountered some strange behavior if I don't read the entire response body; in my case, I stop reading as soon as a certain match is found, and then act on that match; in my specific case, I do not read the last 0 character at the end of the ICAP  RESPMOD body. Basically if I fail to call read_chunk at the end and get the '' string, then this gets read as a request and causes the following error:

code 400, message Bad request syntax ('0')

I have looked at wireshark and the way it looks is that the request is something like this:
RESPMOD icap://127.0.0.1:13440/example ICAP/1.0 [...icap stuff...] [HTTP response] [response body]\n\r\n 0\r\n\r\n

Notice the '0' at the end. The result is that my program handles hte respmod correctly, and then for some reason pyicap tries to read that '0' as a request, producing the above error. However, if I add some code at the end to continue on and read the rest of the response, then this problem disappears.

**Comment by netom** [comment]
AFAIK this cannot be fixed. A solution of any kind is more than welcomed.
