### ISSUE TITLE
Include LICENSE in git repo

### ISSUE THREAD

**Issue by oxisto** [netom/pyicap#9]
From looking at the setup.py, it seems pyicap is licensed under BSD license. Would it be possible to include a LICENSE file in the repo? I am currently thinking about forking pyicap and implementing python3 support and i would feel a bit safer, if the license would be clearly stated.

**Comment by netom** [comment]
Commited 3-clause BSD license in d8472f7b6ff2a5b1874728080c222301d18099fe
